apiVersion: v2
name: unichart
version: 0.0.11
description: A generic Helm chart, supports stateful and statless applications (single deployment each).

maintainers:
  - name: TinyCloud Labs
    url: https://github.com/tinycloud-labs
