apiVersion: v2
name: unichart
version: 0.0.9
description: A generic Helm chart, supports stateful and statless applications.

maintainers:
  - org: https://github.com/tinycloud-labs
  - name: TinyCloud Labs
