apiVersion: v2
name: unichart
version: 0.0.10
description: A generic Helm chart, supports stateful and statless applications.

maintainers:
  - name: TinyCloud Labs
    url: https://github.com/tinycloud-labs
