apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "paperless-ngx.redisHost" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
  serviceName: {{ include "paperless-ngx.redisHeadlessServiceName" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis
        {{- include "paperless-ngx.labels" . | nindent 8 }}
      annotations:
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          volumeMounts:
            - name: shared
              mountPath: /data
              subPath: redisdata
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.shared.existingClaim }}
