apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  replicas: {{ .Values.app.replicaCount | default 1 }}
  selector:
    matchLabels: {{ include "app.selectorLabels" (dict "role" "app" "context" .) | nindent 6 }}-deployment
  template:
    metadata:
      labels: {{ include "app.selectorLabels" (dict "role" "app" "context" .) | nindent 8 }}-deployment
    spec:
      # -- Deployment pods spec --
      containers:
        - name: {{ .Values.app.name }}
          # Decide image name (tag vs digest)
          {{- $image := "" }}
          {{- if .Values.app.image.digest }}
            {{- $image = printf "%s@%s" .Values.app.image.repository .Values.app.image.digest }}
          {{- else }}
            {{- $image = printf "%s:%s" .Values.app.image.repository .Values.app.image.tag }}
          {{- end }}
          image: "{{ $image }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}

          # -- Container Ports --
          {{- range .Values.app.ports }}
          ports:
            - containerPort: {{ .containerPort | quote }}
              name: {{ .name | quote }}
          {{- end }}

          # -- Env- Vars --
          env:
            {{- if .Values.app.dbHostname }}
            - name: {{ .Values.app.dbHostname }}
              value: {{ include "app.dbHeadlessServiceName" . }}
            {{- end }}
            {{- if .Values.app.env }}
            {{- range .Values.app.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          {{- if .Values.app.envFromSecrets.enabled }}

          # -- Secrets Env Vars --
          envFrom:
            {{- range .Values.app.envFromSecrets.secretRefNames }}
            - secretRef:
                name: {{ . | quote }}
            {{- end }}
          {{- end }}

          # -- Volume mounts --
          {{- $vm := .Values.app.volumeMounts | default list }}
          {{- if and .Values.persistence.enabled (gt (len $vm) 0) }}
          volumeMounts:
            {{- range $vm }}
            - name: app-storage
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
          {{- end }}

          # -- Readiness and liveness --
          {{- if .Values.app.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.app.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 5
          {{- end }}
          {{- if .Values.app.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command: {{ toJson .Values.app.livenessProbe.command }}
            initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}
          {{- end }}

      # -- PVC spec --
      {{- if .Values.persistence.enabled }}
      {{- if .Values.persistence.existingClaim }}
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
      {{- else }}
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: {{ include "app.persistenceName" . }}
      {{- end }}
      {{- end }}

      ## -- Affinity spec --
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
