# Defines a StatefulSet for the database.
{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.name" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "app.selectorLabels" (dict "role" "database" "context" .) | nindent 6 }}-statefulset
  serviceName: {{ include "app.dbHeadlessServiceName" . }}
  replicas: {{ .Values.app.replicaCount | default 1 }}
  template:
    metadata:
      labels: {{ include "app.selectorLabels" (dict "role" "database" "context" .) | nindent 8 }}-statefulset
      annotations:
    spec:
      ## -- Stateful pods spec --
      containers:
        - name: {{ include "app.database" . }}
          # Decide image name (tag vs digest)
          {{- $image := "" }}
          {{- if .Values.app.image.digest }}
            {{- $image = printf "%s@%s" .Values.app.image.repository .Values.app.image.digest }}
          {{- else }}
            {{- $image = printf "%s:%s" .Values.app.image.repository .Values.app.image.tag }}
          {{- end }}
          image: "{{ $image }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          {{- if .Values.database.env }}
          env:
            {{- range .Values.database.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          volumeMounts:
            {{- range .Values.database.volumeMounts }}
            - name: db-storage
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}

      # -- PVC spec --
      {{- if .Values.persistence.existingClaim }}
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
      {{- else }}
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: {{ include "app.persistenceName" . }}
      {{- end }}

      ## -- Affinity spec --
      {{- with .Values.database.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
