apiVersion: v2
description: A Helm chart for Installing Github Actions runner deployment
name: gha-runner-deployment
type: application
version: 0.0.1
# This is the version of the Actions Runner Controller that this chart is compatible with.
appVersion: "0.23.7"
