name: Chart Template CI Test

on:
  pull_request:
    paths:
      - 'charts/unichart/**'
  workflow_dispatch:

jobs:
  helm-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - path: charts/unichart
            name: unichart

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Helm Lint
        run: |
          helm lint ${{ matrix.chart.path }} \
            --values ${{ matrix.chart.path }}/ci/ci-values.yaml

      - name: Helm Template Build (CI values)
        run: |
          helm template test ${{ matrix.chart.path }} \
            --values ${{ matrix.chart.path }}/ci/ci-values.yaml \
            --debug
